// <auto-generated />
using System;
using AccessSystem.Infrastructure.Databaase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AccessSystemDbContext))]
    [Migration("20250130182201_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessCardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HolderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccessCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            HolderId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            HolderId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            HolderId = new Guid("00000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessCardRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessCardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessCardId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccessCardRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-1111-1111-1111-111111111111"),
                            AccessCardId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("99999999-2222-2222-2222-222222222222"),
                            AccessCardId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoleId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("99999999-3333-3333-3333-333333333333"),
                            AccessCardId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessClaimEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccessClaims");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-111111111111"),
                            CodeName = "ReceptionAccess"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-222222222222"),
                            CodeName = "MaintenanceAccess"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-333333333333"),
                            CodeName = "RoyalBuffetHallAccess"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000001"),
                            CodeName = "Room001Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000002"),
                            CodeName = "Room002Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000003"),
                            CodeName = "Room003Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000004"),
                            CodeName = "Room004Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000005"),
                            CodeName = "Room005Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000006"),
                            CodeName = "Room006Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000007"),
                            CodeName = "Room007Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000008"),
                            CodeName = "Room008Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000009"),
                            CodeName = "Room009Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000010"),
                            CodeName = "Room010Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000011"),
                            CodeName = "Room011Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000012"),
                            CodeName = "Room012Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000013"),
                            CodeName = "Room013Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000014"),
                            CodeName = "Room014Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000015"),
                            CodeName = "Room015Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000016"),
                            CodeName = "Room016Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000017"),
                            CodeName = "Room017Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000018"),
                            CodeName = "Room018Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000019"),
                            CodeName = "Room019Access"
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-000000000020"),
                            CodeName = "Room020Access"
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessClaimRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessClaimId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessClaimId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccessClaimRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999999"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-111111111111"),
                            RoleId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-0000-4200-999999999999"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-111111111111"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-888888888888"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-222222222222"),
                            RoleId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-0000-4200-888888888888"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-111111111111"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-777777777777"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-333333333333"),
                            RoleId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-0000-4200-777777777777"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-111111111111"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999001"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000001"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999001"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000001"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999002"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000002"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999002"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000002"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999003"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000003"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999003"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000003"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999004"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000004"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999004"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000004"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999005"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000005"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999005"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000005"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999006"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000006"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999006"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000006"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999007"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000007"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999007"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000007"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999008"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000008"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999008"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000008"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999009"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000009"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999009"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000009"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999010"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000010"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999010"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000010"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999011"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000011"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999011"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000011"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999012"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000012"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999012"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000012"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999013"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000013"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999013"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000013"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999014"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000014"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999014"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000014"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999015"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000015"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999015"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000015"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999016"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000016"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000016")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999016"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000016"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999017"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000017"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000017")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999017"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000017"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999018"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000018"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000018")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999018"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000018"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999019"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000019"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000019")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999019"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000019"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-4200-999999999020"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000020"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000020")
                        },
                        new
                        {
                            Id = new Guid("42004200-4200-4200-0000-999999999020"),
                            AccessClaimId = new Guid("42004200-4200-4200-4200-000000000020"),
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessCardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessClaimId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsEntryAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessCardId");

                    b.ToTable("AccessLogEntries");
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleCodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            RoleCodeName = "Receptionist",
                            RoleDescription = "Receptionist role",
                            RoleName = "Receptionist"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            RoleCodeName = "Maintenance",
                            RoleDescription = "Maintenance staff",
                            RoleName = "Maintenance staff"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            RoleCodeName = "CleaningStaff",
                            RoleDescription = "Cleaning staff",
                            RoleName = "Cleaning staff"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            RoleCodeName = "RoyalBuffet",
                            RoleDescription = "Access to the royal buffet",
                            RoleName = "Royal buffet"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            RoleCodeName = "Room001",
                            RoleDescription = "Access to room 001",
                            RoleName = "Room 001"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            RoleCodeName = "Room002",
                            RoleDescription = "Access to room 002",
                            RoleName = "Room 002"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            RoleCodeName = "Room003",
                            RoleDescription = "Access to room 003",
                            RoleName = "Room 003"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            RoleCodeName = "Room004",
                            RoleDescription = "Access to room 004",
                            RoleName = "Room 004"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            RoleCodeName = "Room005",
                            RoleDescription = "Access to room 005",
                            RoleName = "Room 005"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            RoleCodeName = "Room006",
                            RoleDescription = "Access to room 006",
                            RoleName = "Room 006"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            RoleCodeName = "Room007",
                            RoleDescription = "Access to room 007",
                            RoleName = "Room 007"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            RoleCodeName = "Room008",
                            RoleDescription = "Access to room 008",
                            RoleName = "Room 008"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            RoleCodeName = "Room009",
                            RoleDescription = "Access to room 009",
                            RoleName = "Room 009"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            RoleCodeName = "Room010",
                            RoleDescription = "Access to room 010",
                            RoleName = "Room 010"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            RoleCodeName = "Room011",
                            RoleDescription = "Access to room 011",
                            RoleName = "Room 011"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            RoleCodeName = "Room012",
                            RoleDescription = "Access to room 012",
                            RoleName = "Room 012"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            RoleCodeName = "Room013",
                            RoleDescription = "Access to room 013",
                            RoleName = "Room 013"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            RoleCodeName = "Room014",
                            RoleDescription = "Access to room 014",
                            RoleName = "Room 014"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            RoleCodeName = "Room015",
                            RoleDescription = "Access to room 015",
                            RoleName = "Room 015"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            RoleCodeName = "Room016",
                            RoleDescription = "Access to room 016",
                            RoleName = "Room 016"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            RoleCodeName = "Room017",
                            RoleDescription = "Access to room 017",
                            RoleName = "Room 017"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            RoleCodeName = "Room018",
                            RoleDescription = "Access to room 018",
                            RoleName = "Room 018"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            RoleCodeName = "Room019",
                            RoleDescription = "Access to room 019",
                            RoleName = "Room 019"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            RoleCodeName = "Room020",
                            RoleDescription = "Access to room 020",
                            RoleName = "Room 020"
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessCardRole", b =>
                {
                    b.HasOne("AccessSystem.Domain.Entities.AccessCardEntity", "AccessCard")
                        .WithMany()
                        .HasForeignKey("AccessCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessSystem.Domain.Entities.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessCard");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessClaimRole", b =>
                {
                    b.HasOne("AccessSystem.Domain.Entities.AccessClaimEntity", "AccessClaim")
                        .WithMany()
                        .HasForeignKey("AccessClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessSystem.Domain.Entities.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessClaim");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessLogEntry", b =>
                {
                    b.HasOne("AccessSystem.Domain.Entities.AccessCardEntity", "AccessCard")
                        .WithMany("AccessLogEntries")
                        .HasForeignKey("AccessCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessCard");
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessCardEntity", b =>
                {
                    b.Navigation("AccessLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
