// <auto-generated />
using System;
using AccessSystem.Infrastructure.Databaase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AccessSystemDbContext))]
    partial class AccessSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccessCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessCardPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccessCardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessCardId");

                    b.HasIndex("PermissionId");

                    b.ToTable("AccessCardPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-3333-3333-3333-333333333333"),
                            AccessCardId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("99999999-4444-4444-4444-444444444444"),
                            AccessCardId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessCardRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccessCardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessCardId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccessCardRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-1111-1111-1111-111111111111"),
                            AccessCardId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("99999999-2222-2222-2222-222222222222"),
                            AccessCardId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoleId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccessCardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessCardId");

                    b.ToTable("AccessLogEntries");
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionCodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            PermissionCodeName = "Gym"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            PermissionCodeName = "Pool"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            PermissionCodeName = "Maintenance"
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleCodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            RoleCodeName = "Receptionist"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            RoleCodeName = "Guest"
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RoleId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("00000000-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RoleId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("00000000-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RoleId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessCardPermission", b =>
                {
                    b.HasOne("AccessSystem.Domain.Entities.AccessCard", "AccessCard")
                        .WithMany()
                        .HasForeignKey("AccessCardId");

                    b.HasOne("AccessSystem.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId");

                    b.Navigation("AccessCard");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessCardRole", b =>
                {
                    b.HasOne("AccessSystem.Domain.Entities.AccessCard", "AccessCard")
                        .WithMany()
                        .HasForeignKey("AccessCardId");

                    b.HasOne("AccessSystem.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("AccessCard");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessLogEntry", b =>
                {
                    b.HasOne("AccessSystem.Domain.Entities.AccessCard", "AccessCard")
                        .WithMany("AccessLogEntries")
                        .HasForeignKey("AccessCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessCard");
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.Permission", b =>
                {
                    b.OwnsOne("AccessSystem.Domain.ValueObjects.PermissionDescription", "PermissionDescription", b1 =>
                        {
                            b1.Property<Guid>("PermissionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("TEXT")
                                .HasColumnName("PermissionDescription");

                            b1.HasKey("PermissionId");

                            b1.ToTable("Permissions");

                            b1.WithOwner()
                                .HasForeignKey("PermissionId");

                            b1.HasData(
                                new
                                {
                                    PermissionId = new Guid("44444444-4444-4444-4444-444444444444"),
                                    Value = "Gym permission"
                                },
                                new
                                {
                                    PermissionId = new Guid("55555555-5555-5555-5555-555555555555"),
                                    Value = "Pool permission"
                                },
                                new
                                {
                                    PermissionId = new Guid("66666666-6666-6666-6666-666666666666"),
                                    Value = "Maintenance permission"
                                });
                        });

                    b.OwnsOne("AccessSystem.Domain.ValueObjects.PermissionName", "PermissionName", b1 =>
                        {
                            b1.Property<Guid>("PermissionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("PermissionName");

                            b1.HasKey("PermissionId");

                            b1.ToTable("Permissions");

                            b1.WithOwner()
                                .HasForeignKey("PermissionId");

                            b1.HasData(
                                new
                                {
                                    PermissionId = new Guid("44444444-4444-4444-4444-444444444444"),
                                    Value = "Gym"
                                },
                                new
                                {
                                    PermissionId = new Guid("55555555-5555-5555-5555-555555555555"),
                                    Value = "Pool"
                                },
                                new
                                {
                                    PermissionId = new Guid("66666666-6666-6666-6666-666666666666"),
                                    Value = "Maintenance"
                                });
                        });

                    b.Navigation("PermissionDescription")
                        .IsRequired();

                    b.Navigation("PermissionName")
                        .IsRequired();
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.Role", b =>
                {
                    b.OwnsOne("AccessSystem.Domain.ValueObjects.RoleDescription", "RoleDescription", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("TEXT")
                                .HasColumnName("RoleDescription");

                            b1.HasKey("RoleId");

                            b1.ToTable("Roles");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");

                            b1.HasData(
                                new
                                {
                                    RoleId = new Guid("77777777-7777-7777-7777-777777777777"),
                                    Value = "Receptionist role"
                                },
                                new
                                {
                                    RoleId = new Guid("88888888-8888-8888-8888-888888888888"),
                                    Value = "Guest role"
                                });
                        });

                    b.OwnsOne("AccessSystem.Domain.ValueObjects.RoleName", "RoleName", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("RoleName");

                            b1.HasKey("RoleId");

                            b1.ToTable("Roles");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");

                            b1.HasData(
                                new
                                {
                                    RoleId = new Guid("77777777-7777-7777-7777-777777777777"),
                                    Value = "Receptionist"
                                },
                                new
                                {
                                    RoleId = new Guid("88888888-8888-8888-8888-888888888888"),
                                    Value = "Guest role"
                                });
                        });

                    b.Navigation("RoleDescription")
                        .IsRequired();

                    b.Navigation("RoleName")
                        .IsRequired();
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("AccessSystem.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId");

                    b.HasOne("AccessSystem.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AccessSystem.Domain.Entities.AccessCard", b =>
                {
                    b.Navigation("AccessLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
