// <auto-generated />
using System;
using HotelServiceSystem.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelServiceSystem.Infrastructure.Migrations
{
    [DbContext(typeof(HotelServiceSystemDbContext))]
    [Migration("20250127210502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.CleanRoomRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CleanRoomRequestEntity");
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.GuestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GlobalGuestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GuestEntity");
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.PremiumServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelevantRoleCodeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PremiumServiceEntity");
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.PremiumServiceOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PremiumServiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("PremiumServiceId");

                    b.ToTable("PremiumServiceOrderEntity");
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.RoomServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomServiceEntity");
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.RoomServiceOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("RoomServiceOrderEntity");
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.RoomServiceOrderItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoomServiceEntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomServiceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomServiceOrderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomServiceEntityId");

                    b.HasIndex("RoomServiceId");

                    b.HasIndex("RoomServiceOrderId");

                    b.ToTable("RoomServiceOrderItemEntity");
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.CleanRoomRequestEntity", b =>
                {
                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.RoomNumber", "RoomNumber", b1 =>
                        {
                            b1.Property<Guid>("CleanRoomRequestEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasMaxLength(999999)
                                .HasColumnType("INTEGER")
                                .HasColumnName("RoomNumber");

                            b1.HasKey("CleanRoomRequestEntityId");

                            b1.ToTable("CleanRoomRequestEntity");

                            b1.WithOwner()
                                .HasForeignKey("CleanRoomRequestEntityId");
                        });

                    b.Navigation("RoomNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.GuestEntity", b =>
                {
                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.RoomNumber", "GuestRoomNumber", b1 =>
                        {
                            b1.Property<Guid>("GuestEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasMaxLength(999999)
                                .HasColumnType("INTEGER")
                                .HasColumnName("GuestRoomNumber");

                            b1.HasKey("GuestEntityId");

                            b1.ToTable("GuestEntity");

                            b1.WithOwner()
                                .HasForeignKey("GuestEntityId");
                        });

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("GuestEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("GuestEntityId");

                            b1.ToTable("GuestEntity");

                            b1.WithOwner()
                                .HasForeignKey("GuestEntityId");
                        });

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.FirstName", "GuestFirstName", b1 =>
                        {
                            b1.Property<Guid>("GuestEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("GuestFirstName");

                            b1.HasKey("GuestEntityId");

                            b1.ToTable("GuestEntity");

                            b1.WithOwner()
                                .HasForeignKey("GuestEntityId");
                        });

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.LastName", "GuestLastName", b1 =>
                        {
                            b1.Property<Guid>("GuestEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("GuestLastName");

                            b1.HasKey("GuestEntityId");

                            b1.ToTable("GuestEntity");

                            b1.WithOwner()
                                .HasForeignKey("GuestEntityId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("GuestFirstName")
                        .IsRequired();

                    b.Navigation("GuestLastName")
                        .IsRequired();

                    b.Navigation("GuestRoomNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.PremiumServiceEntity", b =>
                {
                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.ServiceDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("PremiumServiceEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Description");

                            b1.HasKey("PremiumServiceEntityId");

                            b1.ToTable("PremiumServiceEntity");

                            b1.WithOwner()
                                .HasForeignKey("PremiumServiceEntityId");
                        });

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.ServiceImage", "Image", b1 =>
                        {
                            b1.Property<Guid>("PremiumServiceEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Image");

                            b1.HasKey("PremiumServiceEntityId");

                            b1.ToTable("PremiumServiceEntity");

                            b1.WithOwner()
                                .HasForeignKey("PremiumServiceEntityId");
                        });

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.ServiceName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PremiumServiceEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("PremiumServiceEntityId");

                            b1.ToTable("PremiumServiceEntity");

                            b1.WithOwner()
                                .HasForeignKey("PremiumServiceEntityId");
                        });

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("PremiumServiceEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(6,4)")
                                .HasColumnName("Price");

                            b1.HasKey("PremiumServiceEntityId");

                            b1.ToTable("PremiumServiceEntity");

                            b1.WithOwner()
                                .HasForeignKey("PremiumServiceEntityId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.PremiumServiceOrderEntity", b =>
                {
                    b.HasOne("HotelServiceSystem.Domain.Entities.GuestEntity", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelServiceSystem.Domain.Entities.PremiumServiceEntity", "PremiumService")
                        .WithMany()
                        .HasForeignKey("PremiumServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("PremiumService");
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.RoomServiceEntity", b =>
                {
                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.ServiceDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("RoomServiceEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Description");

                            b1.HasKey("RoomServiceEntityId");

                            b1.ToTable("RoomServiceEntity");

                            b1.WithOwner()
                                .HasForeignKey("RoomServiceEntityId");
                        });

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.ServiceImage", "Image", b1 =>
                        {
                            b1.Property<Guid>("RoomServiceEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Image");

                            b1.HasKey("RoomServiceEntityId");

                            b1.ToTable("RoomServiceEntity");

                            b1.WithOwner()
                                .HasForeignKey("RoomServiceEntityId");
                        });

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.ServiceName", "Name", b1 =>
                        {
                            b1.Property<Guid>("RoomServiceEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("RoomServiceEntityId");

                            b1.ToTable("RoomServiceEntity");

                            b1.WithOwner()
                                .HasForeignKey("RoomServiceEntityId");
                        });

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("RoomServiceEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(6,4)")
                                .HasColumnName("Price");

                            b1.HasKey("RoomServiceEntityId");

                            b1.ToTable("RoomServiceEntity");

                            b1.WithOwner()
                                .HasForeignKey("RoomServiceEntityId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.RoomServiceOrderEntity", b =>
                {
                    b.HasOne("HotelServiceSystem.Domain.Entities.GuestEntity", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.RoomServiceOrderItemEntity", b =>
                {
                    b.HasOne("HotelServiceSystem.Domain.Entities.RoomServiceEntity", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("RoomServiceEntityId");

                    b.HasOne("HotelServiceSystem.Domain.Entities.RoomServiceEntity", "RoomService")
                        .WithMany()
                        .HasForeignKey("RoomServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelServiceSystem.Domain.Entities.RoomServiceOrderEntity", "RoomServiceOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("RoomServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.Price", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("RoomServiceOrderItemEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(6,4)")
                                .HasColumnName("UnitPrice");

                            b1.HasKey("RoomServiceOrderItemEntityId");

                            b1.ToTable("RoomServiceOrderItemEntity");

                            b1.WithOwner()
                                .HasForeignKey("RoomServiceOrderItemEntityId");
                        });

                    b.OwnsOne("HotelServiceSystem.Domain.ValueObjects.OrderItemAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RoomServiceOrderItemEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Amount");

                            b1.HasKey("RoomServiceOrderItemEntityId");

                            b1.ToTable("RoomServiceOrderItemEntity");

                            b1.WithOwner()
                                .HasForeignKey("RoomServiceOrderItemEntityId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("RoomService");

                    b.Navigation("RoomServiceOrder");

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.RoomServiceEntity", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HotelServiceSystem.Domain.Entities.RoomServiceOrderEntity", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
