// <auto-generated />
using System;
using BillingSystem.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250202225830_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("BillingSystem.Domain.Entities.BillingItem.BillingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BillingItems", (string)null);
                });

            modelBuilder.Entity("BillingSystem.Domain.Entities.Invoice.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("BillingSystem.Domain.Entities.BillingItem.BillingItem", b =>
                {
                    b.OwnsOne("BillingSystem.Domain.Entities.BillingItem.ValueObjects.CustomerId", "CustomerId", b1 =>
                        {
                            b1.Property<Guid>("BillingItemId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("BillingItemId");

                            b1.ToTable("BillingItems");

                            b1.WithOwner()
                                .HasForeignKey("BillingItemId");
                        });

                    b.OwnsOne("BillingSystem.Domain.Entities.BillingItem.ValueObjects.InvoiceId", "InvoiceId", b1 =>
                        {
                            b1.Property<Guid>("BillingItemId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("BillingItemId");

                            b1.ToTable("BillingItems");

                            b1.WithOwner()
                                .HasForeignKey("BillingItemId");
                        });

                    b.OwnsOne("BillingSystem.Domain.Entities.BillingItem.ValueObjects.ItemId", "ItemId", b1 =>
                        {
                            b1.Property<Guid>("BillingItemId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("BillingItemId");

                            b1.ToTable("BillingItems");

                            b1.WithOwner()
                                .HasForeignKey("BillingItemId");
                        });

                    b.OwnsOne("BillingSystem.Domain.Entities.BillingItem.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("BillingItemId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("BillingItemId");

                            b1.ToTable("BillingItems");

                            b1.WithOwner()
                                .HasForeignKey("BillingItemId");
                        });

                    b.OwnsOne("BillingSystem.Domain.Entities.BillingItem.ValueObjects.UnitPrice", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("BillingItemId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("BillingItemId");

                            b1.ToTable("BillingItems");

                            b1.WithOwner()
                                .HasForeignKey("BillingItemId");
                        });

                    b.Navigation("CustomerId")
                        .IsRequired();

                    b.Navigation("InvoiceId")
                        .IsRequired();

                    b.Navigation("ItemId")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("BillingSystem.Domain.Entities.Invoice.Invoice", b =>
                {
                    b.OwnsOne("BillingSystem.Domain.Entities.Invoice.ValueObjects.CurrencyCode", "CurrencyCode", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("BillingSystem.Domain.Entities.Invoice.ValueObjects.FinalPrice", "FinalPrice", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("BillingSystem.Domain.Entities.Invoice.ValueObjects.IsPaid", "IsPaid", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("BillingSystem.Domain.Entities.Invoice.ValueObjects.PaymentId", "PaymentId", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("CurrencyCode")
                        .IsRequired();

                    b.Navigation("FinalPrice")
                        .IsRequired();

                    b.Navigation("IsPaid")
                        .IsRequired();

                    b.Navigation("PaymentId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
